Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: index.handler
      CodeUri: .
      Runtime: nodejs12.x
      Environment:
        Variables:
          SOURCE_BUCKETS: bucket-name
          S3_SAVE_SECRET: secret-key
